-- ============================================================================
-- Front Office — league platform schema
-- Target: PostgreSQL 15+
-- Schema version: 1.0.0
--
-- Design commitments (see front-office-data-model.md for rationale):
--   1. UUID primary keys; every mappable entity carries external_ids JSONB
--   2. Every fact carries provenance: source, ingest batch, confidence, verifier
--   3. Append-only event log; corrections supersede, they never overwrite
--   4. Derived values (standings, cap) are computed, never stored as editable state
--   5. Soft delete only (deleted_at); history stays legible forever
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ---------------------------------------------------------------------------
-- Schema versioning
-- ---------------------------------------------------------------------------

CREATE TABLE schema_version (
    version        TEXT PRIMARY KEY,
    applied_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    notes          TEXT
);
INSERT INTO schema_version (version, notes) VALUES
    ('1.0.1', 'Initial schema + pre-build review fixes: active-GM unique index (B3), idempotency_key & outbox tables (B1/B2), result version column (B4), write-time arithmetic CHECKs (H1)');

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

-- Where a piece of data came from. Ordered loosely by authority, but authority
-- is resolved by data_source_authority below, not by enum order.
CREATE TYPE data_source AS ENUM (
    'manual',        -- typed by a human in the app
    'confirmed',     -- typed by one human, confirmed by the opposing human
    'ocr',           -- parsed from an uploaded screenshot
    'csv_import',    -- bulk import from a commissioner's spreadsheet
    'partner_api',   -- authoritative external feed (reserved for EA / partner)
    'system'         -- generated by the platform (auto-forfeit, sim, rollover)
);

CREATE TYPE seat_status       AS ENUM ('open', 'pending', 'filled', 'suspended', 'vacated');
CREATE TYPE game_status       AS ENUM ('scheduled', 'in_window', 'reported', 'confirmed', 'disputed', 'forfeited', 'postponed', 'simulated', 'voided');
CREATE TYPE game_decision     AS ENUM ('regulation', 'overtime', 'shootout');
CREATE TYPE txn_type          AS ENUM ('trade', 'signing', 'release', 'waiver_claim', 'call_up', 'send_down', 'ir_place', 'ir_activate', 'retire', 'draft_pick', 'reversal');
CREATE TYPE txn_status        AS ENUM ('proposed', 'accepted', 'pending_approval', 'approved', 'rejected', 'executed', 'reversed', 'withdrawn');
CREATE TYPE asset_kind        AS ENUM ('player', 'draft_pick', 'cap_space', 'retained_salary');
CREATE TYPE league_visibility AS ENUM ('public', 'unlisted', 'private');
CREATE TYPE member_role       AS ENUM ('owner', 'commissioner', 'assistant_commissioner', 'gm', 'spectator');

-- Authority ranking. Higher wins during reconciliation. Kept as a table rather
-- than baked into code so a future authoritative feed can be slotted in
-- without a deploy.
CREATE TABLE data_source_authority (
    source     data_source PRIMARY KEY,
    rank       INT NOT NULL,
    notes      TEXT
);
INSERT INTO data_source_authority (source, rank, notes) VALUES
    ('manual',      10, 'Single-party entry'),
    ('ocr',         20, 'Machine-parsed, must be human-confirmed to count'),
    ('csv_import',  30, 'Commissioner bulk load'),
    ('system',      40, 'Platform-generated, deterministic'),
    ('confirmed',   50, 'Two-party agreement'),
    ('partner_api', 90, 'Authoritative external feed — reserved for EA/partner export');

-- ---------------------------------------------------------------------------
-- Identity
-- ---------------------------------------------------------------------------

CREATE TABLE app_user (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    handle          CITEXT UNIQUE,
    display_name    TEXT NOT NULL,
    email           CITEXT UNIQUE NOT NULL,
    timezone        TEXT NOT NULL DEFAULT 'UTC',       -- IANA tz identifier
    platform        TEXT,                              -- 'psn' | 'xbox'
    platform_gamertag TEXT,
    xbox_gamertag   TEXT,
    psn_online_id   TEXT,
    systems_played  TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    primary_identity TEXT CHECK (primary_identity IS NULL OR primary_identity IN ('xbox', 'playstation')),
    country_code    CHAR(2),                           -- ISO 3166-1 alpha-2
    external_ids    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ,
    CHECK (systems_played <@ ARRAY['xbox', 'playstation']::TEXT[]),
    CHECK (
        primary_identity IS NULL
        OR (primary_identity = 'xbox' AND NULLIF(btrim(xbox_gamertag), '') IS NOT NULL
            AND 'xbox' = ANY(systems_played))
        OR (primary_identity = 'playstation' AND NULLIF(btrim(psn_online_id), '') IS NOT NULL
            AND 'playstation' = ANY(systems_played))
    )
);

CREATE TABLE app_user_profile_history (
    id                  BIGSERIAL PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES app_user(id),
    display_name        TEXT NOT NULL,
    timezone            TEXT NOT NULL,
    xbox_gamertag       TEXT,
    psn_online_id       TEXT,
    systems_played      TEXT[] NOT NULL,
    primary_identity    TEXT,
    changed_by          UUID REFERENCES app_user(id),
    recorded_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX app_user_profile_history_user_recorded
    ON app_user_profile_history (user_id, recorded_at DESC);

CREATE FUNCTION reject_app_user_profile_history_mutation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
    RAISE EXCEPTION 'app_user_profile_history is append-only';
END;
$$;
CREATE TRIGGER app_user_profile_history_append_only
BEFORE UPDATE OR DELETE ON app_user_profile_history
FOR EACH ROW EXECUTE FUNCTION reject_app_user_profile_history_mutation();

-- ---------------------------------------------------------------------------
-- League structure
-- ---------------------------------------------------------------------------

CREATE TABLE league (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug            CITEXT UNIQUE NOT NULL,
    name            TEXT NOT NULL,
    visibility      league_visibility NOT NULL DEFAULT 'public',
    primary_color   TEXT,
    secondary_color TEXT,
    logo_url        TEXT,
    owner_user_id   UUID NOT NULL REFERENCES app_user(id),
    external_ids    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);

-- A season is scoped to one game title. This is what makes franchise history
-- survive the annual release cycle.
CREATE TABLE season (
    id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id           UUID NOT NULL REFERENCES league(id),
    ordinal             INT NOT NULL,                  -- 1, 2, 3... within the league
    label               TEXT NOT NULL,                 -- 'Season 1 (NHL 27)'
    game_title          TEXT NOT NULL,                 -- 'NHL27'
    starts_on           DATE,
    ends_on             DATE,
    salary_cap_cents    BIGINT,
    roster_min          INT,
    roster_max          INT,
    games_per_matchup   INT NOT NULL DEFAULT 1,
    points_win          INT NOT NULL DEFAULT 2,
    points_ot_loss      INT NOT NULL DEFAULT 1,
    points_reg_loss     INT NOT NULL DEFAULT 0,
    tiebreakers         TEXT[] NOT NULL DEFAULT ARRAY['points','row','wins','goal_diff','goals_for'],
    is_active           BOOLEAN NOT NULL DEFAULT true,
    external_ids        JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (league_id, ordinal)
);

-- Reference table of real NHL clubs. Kept separate so a franchise can change
-- which club it controls between seasons without losing its own history.
CREATE TABLE nhl_club (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    abbrev       TEXT UNIQUE NOT NULL,                 -- 'CHI'
    name         TEXT NOT NULL,                        -- 'Chicago Blackhawks'
    conference   TEXT,
    division     TEXT,
    external_ids JSONB NOT NULL DEFAULT '{}'::jsonb    -- { "nhl_api": "16", "ea": "..." }
);

-- THE CONTINUITY LAYER. A franchise persists across seasons and across game
-- titles. GMs come and go; the franchise keeps the banner.
CREATE TABLE franchise (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id     UUID NOT NULL REFERENCES league(id),
    name          TEXT NOT NULL,
    founded_season_id UUID REFERENCES season(id),
    external_ids  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);

-- One franchise's participation in one season, controlling one NHL club.
CREATE TABLE team_season (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season_id     UUID NOT NULL REFERENCES season(id),
    franchise_id  UUID NOT NULL REFERENCES franchise(id),
    nhl_club_id   UUID REFERENCES nhl_club(id),
    conference    TEXT,
    division      TEXT,
    seat_status   seat_status NOT NULL DEFAULT 'open',
    external_ids  JSONB NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE (season_id, franchise_id),
    UNIQUE (season_id, nhl_club_id)
);

-- Who is running that team, and when. Append a new row on replacement rather
-- than editing — a mid-season GM change is history, not a correction.
CREATE TABLE gm_assignment (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    team_season_id  UUID NOT NULL REFERENCES team_season(id),
    user_id         UUID NOT NULL REFERENCES app_user(id),
    role            member_role NOT NULL DEFAULT 'gm',
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at        TIMESTAMPTZ,
    end_reason      TEXT                                -- 'resigned' | 'inactive' | 'removed' | 'season_end'
);
-- B3: preventive, not detective. At most one active GM per seat, enforced by
-- the database so two people can never both control (and report for) one
-- franchise between nightly data-quality runs.
CREATE UNIQUE INDEX gm_assignment_one_active
    ON gm_assignment (team_season_id) WHERE ended_at IS NULL;

CREATE TABLE league_membership (
    id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id   UUID NOT NULL REFERENCES league(id),
    user_id     UUID NOT NULL REFERENCES app_user(id),
    role        member_role NOT NULL DEFAULT 'gm',
    joined_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    left_at     TIMESTAMPTZ,
    UNIQUE (league_id, user_id)
);

-- Bylaws as a versioned document. Traceable, diffable, citable in disputes.
CREATE TABLE rulebook_revision (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id    UUID NOT NULL REFERENCES league(id),
    version      TEXT NOT NULL,                        -- '1.0', '1.1'
    body_md      TEXT NOT NULL,
    change_note  TEXT,
    authored_by  UUID NOT NULL REFERENCES app_user(id),
    effective_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (league_id, version)
);

-- ---------------------------------------------------------------------------
-- Players and contracts
-- ---------------------------------------------------------------------------

CREATE TABLE player (
    id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id     UUID REFERENCES league(id),          -- NULL = shared global pool
    full_name     TEXT NOT NULL,
    position      TEXT NOT NULL,                       -- C, LW, RW, D, G
    shoots        CHAR(1),
    birthdate     DATE,
    country_code  CHAR(2),
    -- Reserved for reconciliation against an authoritative roster feed:
    --   { "nhl_api": "8478402", "ea": "...", "eliteprospects": "..." }
    external_ids  JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at    TIMESTAMPTZ
);
CREATE INDEX ON player USING GIN (external_ids jsonb_path_ops);

CREATE TABLE contract (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season_id         UUID NOT NULL REFERENCES season(id),
    player_id         UUID NOT NULL REFERENCES player(id),
    team_season_id    UUID REFERENCES team_season(id),  -- NULL = unsigned / free agent
    cap_hit_cents     BIGINT NOT NULL DEFAULT 0,
    term_years        INT,
    signed_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_after_season_ordinal INT,
    no_trade_clause   BOOLEAN NOT NULL DEFAULT false,
    -- Provenance
    data_source       data_source NOT NULL DEFAULT 'manual',
    ingest_batch_id   UUID,
    superseded_by     UUID REFERENCES contract(id),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON contract (team_season_id) WHERE superseded_by IS NULL;

-- ---------------------------------------------------------------------------
-- Schedule and results
-- ---------------------------------------------------------------------------

-- Matchup windows, not fixed clock times. Coordinating 32 humans across time
-- zones on exact times is the single most common reason leagues stall.
CREATE TABLE game (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season_id       UUID NOT NULL REFERENCES season(id),
    week_number     INT,
    window_opens_at TIMESTAMPTZ NOT NULL,
    window_closes_at TIMESTAMPTZ NOT NULL,
    home_team_season_id UUID NOT NULL REFERENCES team_season(id),
    away_team_season_id UUID NOT NULL REFERENCES team_season(id),
    status          game_status NOT NULL DEFAULT 'scheduled',
    played_at       TIMESTAMPTZ,
    external_ids    JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CHECK (home_team_season_id <> away_team_season_id),
    CHECK (window_closes_at > window_opens_at)
);
CREATE INDEX ON game (season_id, window_closes_at);

-- Append-only. A corrected score is a NEW row that supersedes the old one, so
-- disputes and reversals stay visible in the record.
CREATE TABLE game_result (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    game_id         UUID NOT NULL REFERENCES game(id),
    home_goals      INT NOT NULL CHECK (home_goals >= 0),
    away_goals      INT NOT NULL CHECK (away_goals >= 0),
    decision        game_decision NOT NULL DEFAULT 'regulation',
    -- Provenance: this is the block that makes a future authoritative backfill
    -- a reconciliation instead of a rewrite.
    data_source     data_source NOT NULL DEFAULT 'manual',
    ingest_batch_id UUID,
    confidence      NUMERIC(4,3) CHECK (confidence BETWEEN 0 AND 1),
    reported_by     UUID REFERENCES app_user(id),
    verified_by     UUID REFERENCES app_user(id),
    verified_at     TIMESTAMPTZ,
    superseded_by   UUID REFERENCES game_result(id),
    supersede_reason TEXT,
    -- B4: optimistic-concurrency token for lifecycle transitions (confirm /
    -- dispute / supersede). The FACTS stay immutable; status and verified_by are
    -- lifecycle fields, and racing GMs must not resolve them last-write-wins.
    -- Surfaced as the ETag; state transitions require a matching If-Match.
    version         INT NOT NULL DEFAULT 1,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    -- H1: a regulation result can never be a tie, and an OT/SO result is decided
    -- by exactly one goal. Refused at write time, not merely reported nightly.
    CHECK (home_goals <> away_goals),
    CHECK (decision = 'regulation' OR ABS(home_goals - away_goals) = 1),
    -- A supersede must always state why. Silent edits are the failure mode this
    -- whole platform exists to eliminate.
    CHECK (superseded_by IS NULL OR supersede_reason IS NOT NULL)
);
CREATE INDEX ON game_result (game_id) WHERE superseded_by IS NULL;

CREATE TABLE skater_game_stat (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    game_result_id  UUID NOT NULL REFERENCES game_result(id),
    player_id       UUID NOT NULL REFERENCES player(id),
    team_season_id  UUID NOT NULL REFERENCES team_season(id),
    goals           INT NOT NULL DEFAULT 0,
    assists         INT NOT NULL DEFAULT 0,
    plus_minus      INT NOT NULL DEFAULT 0,
    pim             INT NOT NULL DEFAULT 0,
    shots           INT NOT NULL DEFAULT 0,
    hits            INT NOT NULL DEFAULT 0,
    blocks          INT NOT NULL DEFAULT 0,
    faceoffs_won    INT NOT NULL DEFAULT 0,
    faceoffs_lost   INT NOT NULL DEFAULT 0,
    toi_seconds     INT NOT NULL DEFAULT 0,
    data_source     data_source NOT NULL DEFAULT 'manual',
    ingest_batch_id UUID,
    confidence      NUMERIC(4,3),
    UNIQUE (game_result_id, player_id)
);

CREATE TABLE goalie_game_stat (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    game_result_id  UUID NOT NULL REFERENCES game_result(id),
    player_id       UUID NOT NULL REFERENCES player(id),
    team_season_id  UUID NOT NULL REFERENCES team_season(id),
    shots_against   INT NOT NULL DEFAULT 0,
    saves           INT NOT NULL DEFAULT 0,
    goals_against   INT NOT NULL DEFAULT 0,
    toi_seconds     INT NOT NULL DEFAULT 0,
    decision        TEXT,                              -- 'W' | 'L' | 'OTL' | NULL
    shutout         BOOLEAN NOT NULL DEFAULT false,
    data_source     data_source NOT NULL DEFAULT 'manual',
    ingest_batch_id UUID,
    confidence      NUMERIC(4,3),
    UNIQUE (game_result_id, player_id),
    -- H1: single-row arithmetic that can never legitimately be violated belongs
    -- in a constraint, not the nightly data-quality sweep.
    CHECK (shots_against = saves + goals_against),
    CHECK (shutout = (goals_against = 0))
);

-- ---------------------------------------------------------------------------
-- Transactions — append-only front office ledger
-- ---------------------------------------------------------------------------

CREATE TABLE transaction_event (
    id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    season_id         UUID NOT NULL REFERENCES season(id),
    txn_type          txn_type NOT NULL,
    status            txn_status NOT NULL DEFAULT 'proposed',
    proposed_by       UUID REFERENCES app_user(id),
    proposed_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    resolved_at       TIMESTAMPTZ,
    -- A reversal is a NEW event pointing at the one it undoes. Nothing is
    -- deleted; the wire tells the whole story including the mistakes.
    reverses_txn_id   UUID REFERENCES transaction_event(id),
    note              TEXT,
    data_source       data_source NOT NULL DEFAULT 'manual',
    ingest_batch_id   UUID,
    external_ids      JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE INDEX ON transaction_event (season_id, proposed_at DESC);

CREATE TABLE transaction_asset (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id  UUID NOT NULL REFERENCES transaction_event(id),
    kind            asset_kind NOT NULL,
    player_id       UUID REFERENCES player(id),
    draft_year      INT,
    draft_round     INT,
    amount_cents    BIGINT,
    from_team_season_id UUID REFERENCES team_season(id),
    to_team_season_id   UUID REFERENCES team_season(id)
);

CREATE TABLE transaction_approval (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    transaction_id  UUID NOT NULL REFERENCES transaction_event(id),
    user_id         UUID NOT NULL REFERENCES app_user(id),
    vote            BOOLEAN NOT NULL,
    rationale       TEXT,
    voted_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (transaction_id, user_id)
);

-- ---------------------------------------------------------------------------
-- Ingest and audit
-- ---------------------------------------------------------------------------

-- Every bulk or machine-sourced write belongs to a batch, so it can be
-- inspected, reconciled, or rolled back as a unit. An EA export lands here.
CREATE TABLE ingest_batch (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id       UUID REFERENCES league(id),
    source          data_source NOT NULL,
    source_ref      TEXT,                              -- filename, feed cursor, screenshot id
    submitted_by    UUID REFERENCES app_user(id),
    started_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at    TIMESTAMPTZ,
    row_count       INT,
    conflict_count  INT,
    payload_digest  TEXT,                              -- sha256 of the raw payload
    raw_payload     JSONB
);

CREATE TABLE audit_log (
    id            BIGSERIAL PRIMARY KEY,
    occurred_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    actor_user_id UUID REFERENCES app_user(id),
    league_id     UUID REFERENCES league(id),
    entity_type   TEXT NOT NULL,
    entity_id     UUID NOT NULL,
    action        TEXT NOT NULL,                       -- 'create' | 'update' | 'supersede' | 'execute'
    before        JSONB,
    after         JSONB,
    reason        TEXT
);
CREATE INDEX ON audit_log (league_id, occurred_at DESC);
CREATE INDEX ON audit_log (entity_type, entity_id);

-- B1: idempotency store. Every mutating endpoint accepts an Idempotency-Key;
-- a replay within the window returns the stored response instead of acting
-- twice. This MUST be durable — mobile score submission on bad wifi is exactly
-- the retry case, and Replit restarts mean an in-memory cache is no cache.
-- Same key + different body is a client bug: return 422, never the cached body.
CREATE TABLE idempotency_key (
    user_id         UUID NOT NULL REFERENCES app_user(id),
    key             TEXT NOT NULL,
    request_digest  TEXT NOT NULL,             -- sha256(method + path + body)
    response_status INT,
    response_body   JSONB,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ NOT NULL DEFAULT now() + INTERVAL '24 hours',
    PRIMARY KEY (user_id, key)
);
CREATE INDEX ON idempotency_key (expires_at);   -- sweep expired rows

-- B2: transactional outbox. Side effects (Discord posts, outbound webhooks) are
-- written as rows in the SAME transaction as the business change, then drained
-- by a worker with at-least-once delivery and idempotent handlers. This is what
-- prevents announcing a trade that then rolled back. Present from day one so the
-- first notification uses the pattern instead of a direct in-request API call.
CREATE TABLE outbox (
    id              BIGSERIAL PRIMARY KEY,
    topic           TEXT NOT NULL,             -- 'result.confirmed', 'txn.executed', ...
    payload         JSONB NOT NULL,
    dedupe_key      UUID NOT NULL DEFAULT gen_random_uuid(),  -- consumer dedupe
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    processed_at    TIMESTAMPTZ,
    attempts        INT NOT NULL DEFAULT 0,
    last_error      TEXT,
    next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX ON outbox (next_attempt_at) WHERE processed_at IS NULL;

-- ---------------------------------------------------------------------------
-- Derived views — never stored, always computed
-- ---------------------------------------------------------------------------

-- Only current (non-superseded) results count toward the record.
CREATE VIEW v_active_result AS
SELECT r.*, g.season_id, g.home_team_season_id, g.away_team_season_id
FROM game_result r
JOIN game g ON g.id = r.game_id
WHERE r.superseded_by IS NULL
  AND g.status IN ('confirmed', 'forfeited', 'simulated');

-- One row per team per game, from that team's point of view.
CREATE VIEW v_team_game AS
SELECT season_id, home_team_season_id AS team_season_id, away_team_season_id AS opponent_team_season_id,
       home_goals AS goals_for, away_goals AS goals_against, decision, id AS result_id
FROM v_active_result
UNION ALL
SELECT season_id, away_team_season_id, home_team_season_id,
       away_goals, home_goals, decision, id
FROM v_active_result;

-- Standings. Recomputed on read, so a corrected result fixes the table for free.
CREATE VIEW v_standings AS
SELECT
    tg.season_id,
    tg.team_season_id,
    COUNT(*)                                                       AS gp,
    COUNT(*) FILTER (WHERE goals_for > goals_against)              AS w,
    COUNT(*) FILTER (WHERE goals_for < goals_against
                       AND decision = 'regulation')                AS l,
    COUNT(*) FILTER (WHERE goals_for < goals_against
                       AND decision <> 'regulation')               AS otl,
    COUNT(*) FILTER (WHERE goals_for > goals_against
                       AND decision <> 'shootout')                 AS row_wins,
    SUM(goals_for)                                                 AS gf,
    SUM(goals_against)                                             AS ga,
    SUM(goals_for) - SUM(goals_against)                            AS diff,
      COUNT(*) FILTER (WHERE goals_for > goals_against) * s.points_win
    + COUNT(*) FILTER (WHERE goals_for < goals_against
                         AND decision <> 'regulation') * s.points_ot_loss
    + COUNT(*) FILTER (WHERE goals_for < goals_against
                         AND decision = 'regulation') * s.points_reg_loss
                                                                   AS points
FROM v_team_game tg
JOIN season s ON s.id = tg.season_id
GROUP BY tg.season_id, tg.team_season_id, s.points_win, s.points_ot_loss, s.points_reg_loss;

-- Cap situation, derived from active contracts rather than stored per team.
CREATE VIEW v_cap_position AS
SELECT
    ts.id AS team_season_id,
    s.salary_cap_cents,
    COALESCE(SUM(c.cap_hit_cents), 0)                        AS cap_used_cents,
    s.salary_cap_cents - COALESCE(SUM(c.cap_hit_cents), 0)   AS cap_space_cents,
    COUNT(c.id)                                              AS roster_count,
    (COUNT(c.id) < s.roster_min OR COUNT(c.id) > s.roster_max
     OR COALESCE(SUM(c.cap_hit_cents), 0) > s.salary_cap_cents) AS is_illegal
FROM team_season ts
JOIN season s ON s.id = ts.season_id
LEFT JOIN contract c ON c.team_season_id = ts.id AND c.superseded_by IS NULL
GROUP BY ts.id, s.salary_cap_cents, s.roster_min, s.roster_max;

-- League health, used by the GM marketplace to rank open seats.
CREATE VIEW v_league_health AS
SELECT
    s.league_id,
    s.id AS season_id,
    COUNT(g.id)                                                        AS games_scheduled,
    COUNT(g.id) FILTER (WHERE g.status = 'confirmed')                  AS games_confirmed,
    COUNT(g.id) FILTER (WHERE g.status IN ('forfeited','postponed'))   AS games_missed,
    COUNT(DISTINCT ga.user_id) FILTER (WHERE ga.ended_at IS NULL)      AS active_gms,
    COUNT(DISTINCT ts.id) FILTER (WHERE ts.seat_status = 'open')       AS open_seats
FROM season s
LEFT JOIN game g ON g.season_id = s.id
LEFT JOIN team_season ts ON ts.season_id = s.id
LEFT JOIN gm_assignment ga ON ga.team_season_id = ts.id
GROUP BY s.league_id, s.id;

-- ---------------------------------------------------------------------------
-- Export surface
-- ---------------------------------------------------------------------------
-- The export contract is defined before anyone asks for it. Bumping
-- export_schema_version is how a partner (EA or otherwise) knows the shape
-- changed. See front-office-data-model.md §6 for the payload spec.

CREATE TABLE export_manifest (
    id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    league_id             UUID NOT NULL REFERENCES league(id),
    season_id             UUID REFERENCES season(id),
    export_schema_version TEXT NOT NULL DEFAULT '1.0.0',
    format                TEXT NOT NULL DEFAULT 'json',   -- 'json' | 'csv'
    requested_by          UUID REFERENCES app_user(id),
    generated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    row_counts            JSONB,
    payload_digest        TEXT,
    storage_url           TEXT
);
