// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/Broadcast.tsx": () => import("../components/mockups/landing-variants/Broadcast.tsx"),
  "./components/mockups/landing-variants/Stadium.tsx": () => import("../components/mockups/landing-variants/Stadium.tsx")
};
